[2022-04-27 16:15:59] [ERROR] HTTPConnectionPool(host='192.168.33.123', port=80): Max retries exceeded with url: /api/v0/upgrade_record/system (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D0764A45E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-27 16:17:30] [ERROR] HTTPConnectionPool(host='192.168.33.123', port=80): Max retries exceeded with url: /api/v0/upgrade_record/system (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000197620345E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-27 16:18:07] [ERROR] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2022-04-27 16:18:50] [ERROR] HTTPConnectionPool(host='192.168.33.123', port=80): Max retries exceeded with url: /api/v0/upgrade_record/system (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023750944580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[2022-04-27 16:19:27] [ERROR] HTTPConnectionPool(host='192.168.33.123', port=80): Max retries exceeded with url: /api/v0/upgrade_record/system (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000237508CD970>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
